# -*- coding: utf-8 -*-
"""loginform.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vviQpnLldATkY1_4k-X0-71C20A8KMh4
"""

class LoginForm:
    def __init__(self):
        self.r = []
        self.p = []
        self.e = []
        self.n = []

    def register(self):
        rollnum = int(input("Enter roll number: "))
        if rollnum in self.r:
            print("User already exists")
        password = input("Enter password: ")
        email = input("Enter email: ")
        name = input("Enter name: ")
        self.r.append(rollnum)
        self.p.append(password)
        self.e.append(email)
        self.n.append(name)
        print("User registered")

    def login(self):
        rollnum = int(input("Enter roll number: "))
        password = input("Enter password: ")
        if rollnum in self.r:
            index = self.r.index(rollnum)
            if password == self.p[index]:
                print("Login successful")
            else:
                print("Incorrect password")
        else:
            print("User not found")
    def viewprofile(self):
        rollnumber = int(input("Enter roll number: "))
        password = input("Enter password: ")
        if rollnumber in self.r:
            index = self.r.index(rollnumber)
            if password == self.p[index]:
                print("Roll number is:", self.r[index])
                print("Email is:", self.e[index])
                print("Name is:", self.n[index])
            else:
                print("Incorrect password")


if __name__ == "__main__":
    print("PRINT 1 FOR SIGN UP\nPRINT 2 FOR LOGIN \nPRINT 3 FOR VIEWING PROFILE")
    ch=int(input("ENTER CHOICE"))
    login_form = LoginForm()
    while ch<4:
        if ch==1:
            login_form.register()
        if ch==2:
           login_form.login()
        if ch==3:
           login_form.viewprofile()
        if ch==4:
            break